### PR TITLE
[267] Fix for Image with space in name failed to display after import…

### PR DESCRIPTION
**Pull request by Yeronimo**
Image with space in name failed to display after imported to Azure. #267

### CODE REVIEW

**Comment by Yeronimo** [comment]
Related to issues #225 #226

**Comment by Kookabura** [comment]
Hi all
I think this approach is better:

```
var encodedFileName = HttpUtility.UrlEncode(fileName);
if (textField.Contains(fileName) || textField.IndexOf(encodedFileName, StringComparison.OrdinalIgnoreCase) >= 0 || textField.Contains("_thumb_" + att.AttOriginId))
```

It works not only for spaces but for non-english characters and Jira thumbnails as well.

**Review by tung-nt-niteco — APPROVED** [review]
Thanks for the fix, it works, I have a fix for myself, too: https://github.com/tung-nt-niteco/jira-azuredevops-migrator/commit/95d9d5c8d3041239bf162e81bc74846884a0bf27
based on what Kookabura recommended, worked on my environment.

**Comment by Alexander-Hjelm** [comment]
Apply Kookabura's fix, then verify and merge

**Pull request closed without merging**
