### PR TITLE
Bugfix/correctly map description with whitespace

### PR DESCRIPTION
**Pull request by Alexander-Hjelm**
Supersedes https://github.com/solidify/jira-azuredevops-migrator/pull/597

### CODE REVIEW

**Comment by Alexander-Hjelm** [comment]
@moerketh, I successfully reproduced the erroneous behavior, but your fix doesn't quite seem to do the trick for me. I still get the following error on the ADO side:
```
  File "D:\a\1\s\jira-azuredevops-migrator-smoke-tests\smoke-tests.py", line 151, in <module>
    if ado_work_item["fields"]["System.Description"] in jira_issue["fields"]["description"]:
KeyError: 'System.Description'
```

But maybe I'm missing something?

History of my issue:

image

**Comment by Alexander-Hjelm** [comment]
Nevermind. The fix works as intended. I fixed the integration tests so they ignore descriptions with only whitespace.

The only quirk is that the `System.Description` field will not be set on the target ADO work item. When retrieving the target work item, it will not have a Description field. I don't know if this is the intended behavior? @moerketh 

Adding @madkoo as reviewer

**Comment by Alexander-Hjelm** [comment]
Integration tests passing: https://dev.azure.com/solidify/Internal/_build?definitionId=138&_a=summary

**Review by madkoo — APPROVED** [review]
Looks ok

**Comment by moerketh** [comment]
Thanks @Alexander-Hjelm
Ah, a quirk indeed. I didn't check that because in this case I don't have specific requirements for the System.Description field. I would have expected it to be set, but if it's not it's okay for me.

**Comment by Alexander-Hjelm** [comment]
Let’s keep it this way for now :)
________________________________

**Pull request merged**
