### PR TITLE
migrate to dotnet core csproj for all projects except for wi-import

### PR DESCRIPTION
**Pull request by chekkan**
I was not able migrate the wi-import.csproj because of the dependency to `Microsoft.TeamFoundationServer.Client` package in wi-import project.

### CODE REVIEW

**Comment by MOlausson** [comment]
Hi @chekkan. What is your intention with this PR? What do you see as the reasons to migrate to .net core?

**Comment by chekkan** [comment]
I wanted to run these tools on my mac. I understand that perhaps i could have done it using Mono somehow. However, with this change, I can at least run the `jira-export` project on a mac/linux. 

And perhaps, at a later stage the build can package the runtime with the release of the binaries so that users wont have to install the runtime in order to run the tools. Making it easier for non technical users use it.

**Comment by MOlausson** [comment]
Got it. Yes, we have heard that request and it makes complete sense. I'll see how we best approach this.

**Comment by RonnyA** [comment]
The DevOps NuGet packages has been updated ref https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops
If you look at the latest preview releases of the NuGet packages (currently '16.152.0-preview') a lot of work as been put into them to make them work in NetStandard

There is one thing that is a problem moving wi-import forward to .NET Core:
* Microsoft.TeamFoundationServer.ExtendedClient package doesn't have NetStandard support
* The Microsoft.TeamFoundationServer.ExtendedClient currently doesn't support a NetStandard compliant version. This package includes our older SOAP object model, which has been replaced by our newer REST object model. 

If the code in wi-import/Agent.cs can be rewritten to support the REST API instead of the old SOAP model then wi-import could also be moved to NetStandard by dropping the dependency to Microsoft.TeamfoundationServer.ExtendedClient

And then we can make it work on Linux as well :)

**Comment by MOlausson** [comment]
Thanks for your contribution @chekkan. I'm closing this PR as we've decided to take a different approact for the migration to .net core which we will target in v3 of the migration tools.

**Pull request closed without merging**
