### PR TITLE
Resolved inability to use mapping on custom fields on initial revision.

### PR DESCRIPTION
**Pull request by sgtwilko**
*Add copy of CustomeField_XXX using real jira field name in order that mapping values works on initial revision.*

We ran into an issue where we were unable to output values that used the `mapping` feature with custom Jira fields.

When debugging it turned out that the fields in the initial revision used the internal name `CustomField_12345` and not the visible name.
I also spotted that switching the mapping on and off caused the fields to turn up at different revisions in the output.

This indicated to me that the initial parsing of the Jira was probably treating the initial revision differently from all the others.

This change fixes this issue.

I haven't added a test, can you advise how best I can add a test which uses custom fields and mapping?
It looked like these were being tested in very different ways and I wasn't sure the best way/place to proceed.

### CODE REVIEW

**Comment by sgtwilko** [comment]
@Alexander-Hjelm  Anything else you need from me on this?
I'd like to know how best to add the unit test, it seemed non-trivial.

**Comment by Alexander-Hjelm** [comment]
@sgtwilko , nothing more as far as I can see. A unit test would be a nice-to-have. I'd say look at the existing JiraItem tests in https://github.com/solidify/jira-azuredevops-migrator/blob/master/src/WorkItemMigrator/tests/Migration.Jira-Export.Tests/JiraItemTests.cs

Inside the issueObject you can pass issue fields as a key-value structure:

```
            JObject remoteIssue = new JObject
            {
                { "id", issueId },
                { "key", issueKey },
                { "fields", fields },
                { "renderedFields", renderedFields }
            };
```

**Comment by sgtwilko** [comment]
@Alexander-Hjelm  I updated this, not to include a test (I'll hopefully get to that), but to include further changes.
It looks like most of the issues I was seeing were because our Jira Server was returning the actual name in the change history, not the internal `customfield_21002` name.

This caused the `IfChanged` function to not be able to find the value, and most of the revisions were then empty.

**Comment by Alexander-Hjelm** [comment]
@sgtwilko I have found that the most reliable way to list the actual key of the issueField is to GET the issue through the API:

```
https://<your-jira-instance>.atlassian.net/rest/api/2/issue/createmeta?projectKeys=<$projectKey>&issuetypeNames=<$issueType>&expand=projects.issuetypes.fields
```

**Comment by Alexander-Hjelm** [comment]
Ok, makes sense. Let me merge into a feature branch of the mother repo to run some integration tests, just to verify that this doesn't break anything.

Is this PR ready for merging now? @sgtwilko

**Comment by sgtwilko** [comment]
Well, other than I've not had a chance to add unit tests, I believe so.
I've run this on our project and not seen any issue.

**Comment by Alexander-Hjelm** [comment]
Will wait with merging this one then. I can add tests too later, but currently focusing on other bugs, so that will not be my highest priority :)

**Pull request merged**
